feat: add deserialization of plonk circom types
TaceoLabs/collaborative-circom pull request #128
Opened 2024-08-01 14:11 UTC by 0xThemis

Adds functionality to deserialize the following PLONK artifacts form circom:

- proof
- verification key
- zkey

2024-08-01 14:47 UTC, dkales requested changes
This also is a breaking change since it modifies the public interface of various crates.

2024-08-01 14:47 UTC, dkales commented on circom-types/src/groth16/r1cs.rs
I think from an organization standpoint r1cs should not be below groth16, since it is not only for that, just leave it at the top lvl

2024-08-01 14:47 UTC, dkales commented on circom-types/src/plonk/mod.rs
Would like it better if we just re-export the types here with `pub use` instead of nesting deeper for often only a single type, and make the mods private

2024-08-01 14:47 UTC, dkales commented on circom-types/src/plonk/verification_key.rs
> +/// Represents a verification key in JSON format that was created by circom. Supports de/serialization using [`serde`].
Does the verification key not need a separate format like the proof? Or other way round: why does the proof need 2 different types and this not?

2024-08-01 14:47 UTC, dkales commented on circom-types/src/plonk/zkey.rs
> +        //TODO: why domain size + 6?
do we have an answer here?

2024-08-01 14:47 UTC, dkales commented on circom-types/src/plonk/zkey.rs
> +            additions: additions.unwrap()?,
maybe add a comment why these unwraps are ok

2024-08-02 07:29 UTC, 0xThemis commented on circom-types/src/groth16/r1cs.rs
Moved it back - we may need a structural overhaul in the near future I think

2024-08-02 07:30 UTC, 0xThemis commented on circom-types/src/plonk/mod.rs
Did that, but only for this file. Maybe do that also for the other ones in a future PR?

2024-08-02 07:32 UTC, 0xThemis commented on circom-types/src/plonk/zkey.rs
> +        //TODO: why domain size + 6?
Unfortunately, not.

2024-08-02 07:35 UTC, 0xThemis commented on circom-types/src/plonk/zkey.rs
> +            additions: additions.unwrap()?,
Done

2024-08-02 08:18 UTC, dkales approved these changes

2024-08-02 08:29 UTC, merged